apiVersion: v1
kind: Service
metadata:
  name: pyroscope
  labels:
    app: pyroscope
spec:
  type: ClusterIP
  ports:
    - port: 4040
      targetPort: 4040
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: pyroscope