global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'auth-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-api:80']
  - job_name: 'bank-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['bank-api:80']
  - job_name: 'bank-spa'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['bank-api:80']
  - job_name: 'envoy'
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ['envoy-admin:9901']