{{- range .Values.instances }}
{{- if .initScriptFolder }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.name" (dict "name" .name) }}-init
data:
  {{- $files := .initScriptFolder }}
  {{- range $path, $bytes := $.Files.Glob (printf "files/%s/*" $files) }}
  {{ base $path }}: |-
{{ $bytes | toString | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
