name: bank-api
containerPort: 80
replicaCount: 1
image:
  repository: romanzanotelli/bank-api
  tag: "latest"
  pullPolicy: IfNotPresent
env:
  database_url: "postgres://api_user:super-secure-password@ledger-db:5432/bank_db"
  jwt_secret: "something-super-duper-extra-secret!!!"
postgres:
  host: bank-db
  port: 5432
  waitTimeoutSeconds: 30
  waitSleepSeconds: 5