apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: grafana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: dashboards
              mountPath: /etc/grafana/provisioning/dashboards/
              readOnly: true
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards.yaml
              subPath: dashboards.yaml
              readOnly: true
            - name: config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
              readOnly: true
      volumes:
        - name: dashboards
          configMap:
            name: grafana-dashboards
        - name: dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        - name: config
          configMap:
            name: grafana-config