apiVersion: v1
kind: Secret
metadata:
  name: envoy-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "certs/tls.chain.crt" | b64enc }}
  tls.key: {{ .Files.Get "certs/tls.key" | b64enc }}