apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}-config
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: {{ .Values.service.port }}
    schema_config:
      configs:
        - from: 2025-07-15
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage_config:
      tsdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
      filesystem:
        directory: /var/loki/chunks
    limits_config:
      retention_period: 168h
    common:
      path_prefix: /loki
      replication_factor: 1
      ring:
        kvstore:
          store: memberlist
    memberlist:
      join_members:
        - {{ printf "%s-0.%s.%s.svc.cluster.local:7946" (include "loki.fullname" .) (include "loki.fullname" .) .Release.Namespace }}
    distributor:
      ring:
        kvstore:
          store: memberlist