core:
  auth-api:
    name: auth-api
    containerPort: 80
    replicaCount: 1
    image:
      repository: romanzanotelli/auth-api
      tag: "latest"
      pullPolicy: IfNotPresent
    env:
      database_url: "postgres://api_user:super-secure-password@demo-auth-db:5432/auth_db"
      jwt_duration: "3600"
      jwt_secret: "something-super-duper-extra-secret!!!"
      jwt_iss: "auth-api"

  bank-api:
    name: bank-api
    containerPort: 80
    replicaCount: 1
    image:
      repository: romanzanotelli/bank-api
      tag: "latest"
      pullPolicy: IfNotPresent
    env:
      database_url: "postgres://api_user:super-secure-password@demo-ledger-db:5432/ledger_db"
      jwt_secret: "something-super-duper-extra-secret!!!"
  
  bank-spa:
    name: bank-spa
    image:
      repository: romanzanotelli/bank-spa
      tag: latest
      pullPolicy: IfNotPresent
    replicaCount: 1
    containerPort: 80
    env:
      csp: |
        default-src 'self';
        connect-src 'self' https://localhost;
        script-src 'self';
        script-src-attr 'self' 'unsafe-inline';
        style-src 'self' 'unsafe-inline';
        style-src-elem 'self' 'unsafe-inline';
        font-src 'self';
        img-src 'self' data:;

  postgre:
    image:
      repository: postgres
      tag: "16.3"
      pullPolicy: IfNotPresent
    instances:
      - name: auth-db
        port: 5432
        storage: 1Gi
        password: "super-secure-root-password"
        initScriptFolder: "init-scripts-auth"
      - name: ledger-db
        port: 5432
        storage: 1Gi
        password: "super-secure-root-password"
        initScriptFolder: "init-scripts-ledger"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi